apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-db-creation-script
data:
  mysql_usermgmt.sql: |
    DROP DATABASE IS EXISTS webappdb;
    CREATE DATABASE webappdb;
###something called as user data bootstraping script.    
