apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  completions: 2 #this job is going to run by two pods
  parallelism: 2 ##by default we put completion two means this job is being completed by two pod one by pne
  ##parallelism : it will create both the pod samultenously and run your job
  template:
    spec:
      containers:
      - name: node-app-job 
        image: alpine
        command: ["echo","welcome to my Node APP1"]
      restartPolicy: Never #if your master machine get restarted the job will restart again. 
