apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  template:
    spec:
      containers:
      - name: node-app-job 
        image: alpine
        command: ["echo","welcome to my Node APP1"]
      restartPolicy: Never #if your master machine get restarted the job will restart again. 
