apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD #this env varaible is avaiable iun the container image
            valueFrom:
              secretKeyRef:
                name: mysql-db-passowrd
                key: password
        ports:
        - containerPort: 3306
      ###when i deploy this container. it should map with your pvc
        volumeMounts:
          - name: mysql-pvc-1 
            mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: task-pv-claim