apiVersion: v1
#####kind will be pod 
kind: Pod ##pod is the name of the api
metadata:
  name: webserver #using metadata name we define the pod name
spec: ##we are define the specification about the pod
  containers: ##inside the pod we are going to run a container
    - image: nginx ##this is the name of the container-image
      name: nginx 
    - image: consul
      name: consul 
###to deploy your container workload in k8s
