apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-pv-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
