apiVersion: v1 
kind: ResourceQuota
metadata:
  name: compute-resource
  namespace: dev 
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "4"
    secrets: "10"
    services: "10"
    configmap: "10"