apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  namespace: project-hamster
  name: processor
rules:
- apiGroups: ["*"]
  resources: ["secret","configmap"]
  verbs: ["get","list","watch","create"]
  