apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 10Gi #this 10 Gb is like a thin provisioing. but if i am using 1 gb that storage will be usable
    ###but my storage expansion will go upto 10Gb
  volumeMode: Filesystem #according to your file system windows ntfs ext
  accessModes:
    - ReadWriteOnce #readwritemany #readonly
  #persistentVolumeReclaimPolicy: Recycle #immediate when you delete your pod the volume will be also deleted
  ###against this we are goign to create a pod if the pod get deleted volume will be there but 
  ##all the data will be clean up. 
  #storageClassName: slow, EBS azure blob storage
 # Standard, Premuim Ultradisk
  #HDD,SSD,Nvm
  ###normal hdd we are using
  hostPath:
    path: /mnt/data
  #mountOptions:
   # - hard
    #- nfsvers=4.1
  #nfs:
   # path: /tmp
    #server: 172.17.0.2
