apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-clusterip-service
  labels: 
    app: usermgmt-restapp
spec:
  type: NodePort
  selector:
    app: usermgmt-webapp
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 31232